config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:show, :index, :new,:create, :edit,:update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length:{minimum:6, maximum:100}
    validates :descriptin, presence: true,length:{minimum:10, maximum:300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  def hello
#     render html:'hello world!'
#  end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
   
  
  
  end

  def index
    @articles = Article.all
  
  end

  def new
    @articles = Article.new
   
  end

  def create
    @article =Article.new(params_set)

    if @article.save
     flash[:notice] = "Article was creates sucessfully"
     redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  

  end

  def  update
   
    if @article.update(params_set)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
   
    @article.destroy
    redirect_to articles_path(@article)
  end

  private
  def set_article

  @article = Article.find(params[:id])
  end

  def params_set
    params.require(:article).permit(:title, :descriptin)
  end




  # def create
  #   @article = Article.new(article_params)

  #   respond_to do |format|
  #     if @article.save
  #       format.html { redirect_to @article, notice: 'Article was successfully created.' }
  #       format.json { render :show, status: :created, location: @article }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end


  # before_action :set_article, only: [:show, :edit, :update, :destroy]

  # # GET /articles
  # # GET /articles.json
  # def index
  #   @articles = Article.all
  # end

  # # GET /articles/1
  # # GET /articles/1.json
  # def show
  # end

  # # GET /articles/new
  # def new
  #   @article = Article.new
  # end

  # # GET /articles/1/edit
  # def edit
  # end

  # # POST /articles
  # # POST /articles.json
  # def create
  #   @article = Article.new(article_params)

  #   respond_to do |format|
  #     if @article.save
  #       format.html { redirect_to @article, notice: 'Article was successfully created.' }
  #       format.json { render :show, status: :created, location: @article }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /articles/1
  # # PATCH/PUT /articles/1.json
  # def update
  #   respond_to do |format|
  #     if @article.update(article_params)
  #       format.html { redirect_to @article, notice: 'Article was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @article }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /articles/1
  # # DELETE /articles/1.json
  # def destroy
  #   @article.destroy
  #   respond_to do |format|
  #     format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_article
  #     @article = Article.find(params[:id])
  #   end

  #   # Only allow a list of trusted parameters through.
  #   def article_params
  #     params.require(:article).permit(:title, :descriptin)
  #   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>edit  a new article</h1>



<% if @article.errors.any? %>
<h2> errors</th>
<ul>
 <% @article.errors.full_messages.each do |msg| %>
  <li>  <%= msg %></li>

 <% end %>
 </ul>

<% end %>
 
<%= form_with(model: @article, local: true)  do |f| %>
  <p> 
    <%= f.label :title %><br/> 
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :descriptin %><br/> 
    <%= f.text_area :descriptin %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

app/views/articles/index.html.erb
<h1>Article listing page</Article></h1>
<table>
<thead>
<tr>
<th>Title
</th>
<th>
Description
</th>
<th colspan="3">Actions</th>
</tr>



</thead>
<tbody>
<% @articles.each do |article| %>
<tr>
<td><%= article.title %></td>
<td><%= article.descriptin %></td>
<td><%= link_to 'Edit',  edit_article_path(article) %>   <%= link_to 'Show', article_path(article) %>   <%= link_to 'Delete', article_path(article), method: :delete %></td>
</tr>
<% end %>

</tbody>
</table>

<%= link_to 'create new article', new_article_path %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>



<% if @article.errors.any? %>
<h2> errors</th>
<ul>
 <% @article.errors.full_messages.each do |msg| %>
  <li>  <%= msg %></li>

 <% end %>
 </ul>

<% end %>
 
<%= form_with scope: :article, url: articles_path, local: true do |f| %>
  <p> 
    <%= f.label :title %><br/> 
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :descriptin %><br/> 
    <%= f.text_area :descriptin %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>


<p>
<%= link_to 'Cancel and return to articles listing', articles_path %> 
</p>

app/views/articles/show.html.erb
<h1>showing article</h1>
<p><strong>title:</strong><%= @article.title %></p>
<p><strong>description:</strong><%= @article.descriptin %></p>

<%= link_to 'Edit', edit_article_path(@article) %>  |
<%= link_to 'Delete', article_path(@article), method: :delete, data:{ confirm:"are you sure?"} %> |
<%= link_to 'Return Articles Listing',articles_path(@article) %> 

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <%= msg %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NameOfApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name,msg| %>
    <%= msg %>

   <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>this is about page</h1>

app/views/pages/home.html.erb
<h1>Home page</h1>

<%= link_to 'articles', articles_path %>
<%= link_to 'About Page', about_path %>